

BootStrap: shub
From: trcook/DL_containers:base


%runscript
    chk_nvidia_uvm=$(grep nvidia_uvm /proc/modules)


    exec /usr/bin/python3 "$@"

%post
    apt-get install -y python3-tk
    # Install TensorFlow GPU version
    pip3 install --upgrade tensorflow-gpu\
    keras\
    protobuf
    #pip3 install --upgrade 
    # keras
    #pip3 install --upgrade keras

