



BootStrap: shub
From: shub://trcook/tf:base


%runscript
    chk_nvidia_uvm=$(grep nvidia_uvm /proc/modules)


    exec /usr/bin/python3 "$@"

%post
    apt-get install -y python3-tk
    # Install TensorFlow GPU version
    pip3 install --upgrade tensorflow-gpu\
    keras\
    protobuf\
    tensorforce\
    snakemake\
    pandas\
    anytree\
    jinja2\
    ruamel.yaml\
    gym\

